/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : bigint,
  'personality' : string,
  'isMature' : boolean,
  'contentWarnings' : Array<string>,
  'traits' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'avatarUrl' : [] | [string],
  'backstory' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'userId' : Principal,
  'role' : string,
  'timestamp' : Time,
  'characterId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'displayName' : string,
  'hasAcknowledgedAge' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[bigint, string, string], ChatMessage>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearChatHistory' : ActorMethod<[bigint], undefined>,
  'createCharacter' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      boolean,
      [] | [string],
    ],
    Character
  >,
  'deleteCharacter' : ActorMethod<[bigint], undefined>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacter' : ActorMethod<[bigint], [] | [Character]>,
  'getCharactersByUser' : ActorMethod<[Principal], Array<Character>>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string, boolean], UserProfile>,
  'updateCharacter' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      boolean,
      [] | [string],
    ],
    Character
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];