/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : IDL.Principal,
  'role' : IDL.Text,
  'timestamp' : Time,
  'characterId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Character = IDL.Record({
  'id' : IDL.Nat,
  'personality' : IDL.Text,
  'isMature' : IDL.Bool,
  'contentWarnings' : IDL.Vec(IDL.Text),
  'traits' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'backstory' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'hasAcknowledgedAge' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [ChatMessage], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearChatHistory' : IDL.Func([IDL.Nat], [], []),
  'createCharacter' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [Character],
      [],
    ),
  'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
  'getCharactersByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Character)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [UserProfile],
      [],
    ),
  'updateCharacter' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [Character],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : IDL.Principal,
    'role' : IDL.Text,
    'timestamp' : Time,
    'characterId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'personality' : IDL.Text,
    'isMature' : IDL.Bool,
    'contentWarnings' : IDL.Vec(IDL.Text),
    'traits' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'backstory' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'hasAcknowledgedAge' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [ChatMessage], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearChatHistory' : IDL.Func([IDL.Nat], [], []),
    'createCharacter' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [Character],
        [],
      ),
    'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
    'getCharactersByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Character)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [UserProfile],
        [],
      ),
    'updateCharacter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [Character],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };